// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace SampleCodedUITest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Ereignisprotokoll
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinButton uISimplicStudioButton = this.UIItemWindow.UIAusgeführteAnwendungToolBar.UISimplicStudioButton;
            WpfButton uIEreignisprotokollButton = this.UISimplicStudio2015spiWindow.UIStartPageCustom.UITileScrollViewerPane.UIEreignisprotokollButton;
            WpfCustom uIM_gridSearchGridCustom = this.UISimplicStudio2015spiWindow.UIDataGridKeyboardContCustom.UIDataGridRibbonContexCustom.UIM_gridSearchGridCustom;
            WpfButton uIVollständigladenButton = this.UISimplicStudio2015spiWindow.UIDataGridKeyboardContCustom.UIDataGridRibbonContexCustom.UIM_gridSearchGridCustom.UIVollständigladenButton;
            WpfControl uIDatumHeaderItem = this.UISimplicStudio2015spiWindow.UIRadGridViewTable.UIPART_HeaderRowHeader.UIDatumHeaderItem;
            WpfText uISchweregradText = this.UISimplicStudio2015spiWindow.UIRadGridViewTable.UISchweregradHeaderItem.UISchweregradText;
            WpfButton uISaveLyoutButtonButton = this.UISimplicStudio2015spiWindow.UIDataGridKeyboardContCustom.UIDataGridRibbonContexCustom.UIM_gridSearchGridCustom.UISaveLyoutButtonButton;
            WpfList uIGridViewGroupPanelList = this.UISimplicStudio2015spiWindow.UIRadGridViewTable.UIGridViewGroupPanelList;
            WpfButton uIAusblendenButton = this.UISimplicStudio2015spiWindow.UIRadSplitContainerCustom.UIRadPaneGroupTabList.UIEreignisprotokollTabPage.UIAusblendenButton;
            WpfButton uIPART_CloseButtonButton = this.UISimplicStudio2015spiWindow.UIM_gridSearchGridCustom.UIRadGridViewTable.UISchweregradListItem.UIPART_CloseButtonButton;
            WpfButton uISaveLyoutButtonButton1 = this.UISimplicStudio2015spiWindow.UIM_gridSearchGridCustom.UISaveLyoutButtonButton;
            WpfButton uIAusblendenButton1 = this.UISimplicStudio2015spiWindow.UIRadSplitContainerCustom.UIRadPaneGroupTabList.UIEreignisprotokollTabPage1.UIAusblendenButton;
            WpfButton uIVollständigladenButton1 = this.UISimplicStudio2015spiWindow.UIDataGridRibbonContexCustom.UIM_gridSearchGridCustom.UIVollständigladenButton;
            #endregion

            // Click 'Simplic Studio' button
            Mouse.Click(uISimplicStudioButton, new Point(24, 19));

            // Click 'Ereignisprotokoll' button
            Mouse.Click(uIEreignisprotokollButton, new Point(172, 56));

            // Click 'm_gridSearchGrid' custom control
            Mouse.Click(uIM_gridSearchGridCustom, new Point(144, 789));

            // Click 'Vollständig laden' button
            Mouse.Click(uIVollständigladenButton, new Point(55, 6));

            // Click 'Datum' HeaderItem
            Mouse.Click(uIDatumHeaderItem, new Point(44, 5));

            // Click 'Schweregrad' label
            Mouse.Click(uISchweregradText, new Point(35, 8));

            // Click 'saveLyoutButton' button
            Mouse.Click(uISaveLyoutButtonButton, new Point(12, 7));

            // Move 'Schweregrad' label to 'GridViewGroupPanel' list box
            uIGridViewGroupPanelList.EnsureClickable(new Point(750, 20));
            Mouse.StartDragging(uISchweregradText, new Point(32, 10));
            Mouse.StopDragging(uIGridViewGroupPanelList, new Point(750, 20));

            // Click 'saveLyoutButton' button
            Mouse.Click(uISaveLyoutButtonButton, new Point(10, 12));

            // Click 'Ausblenden' button
            Mouse.Click(uIAusblendenButton, new Point(7, 7));

            // Click 'Ereignisprotokoll' button
            Mouse.Click(uIEreignisprotokollButton, new Point(49, 62));

            // Click 'PART_CloseButton' button
            Mouse.Click(uIPART_CloseButtonButton, new Point(2, 3));

            // Click 'saveLyoutButton' button
            Mouse.Click(uISaveLyoutButtonButton1, new Point(9, 7));

            // Click 'Ausblenden' button
            Mouse.Click(uIAusblendenButton1, new Point(3, 4));

            // Click 'Ereignisprotokoll' button
            Mouse.Click(uIEreignisprotokollButton, new Point(52, 39));

            // Click 'Vollständig laden' button
            Mouse.Click(uIVollständigladenButton1, new Point(73, 10));
        }
        
        /// <summary>
        /// LoadGrid
        /// </summary>
        public void RecordedMethod2()
        {
            #region Variable Declarations
            WpfButton uIEreignisprotokollButton = this.UISimplicStudio2015spiWindow.UIStartPageCustom.UITileScrollViewerPane.UIEreignisprotokollButton;
            WpfButton uIVollständigladenButton = this.UISimplicStudio2015spiWindow.UIDataGridRibbonContexCustom.UIM_gridSearchGridCustom.UIVollständigladenButton;
            WpfButton uIMyRefreshButtonButton = this.UISimplicStudio2015spiWindow.UIDataGridRibbonContexCustom.UIM_searchBoxGridsCustom.UIMyRefreshButtonButton;
            WpfButton uIAusblendenButton = this.UISimplicStudio2015spiWindow.UIRadSplitContainerCustom.UIRadPaneGroupTabList.UIEreignisprotokollTabPage.UIAusblendenButton;
            #endregion

            // Click 'Ereignisprotokoll' button
            Mouse.Click(uIEreignisprotokollButton, new Point(112, 36));

            // Click 'Vollständig laden' button
            Mouse.Click(uIVollständigladenButton, new Point(57, 13));

            // Click 'myRefreshButton' button
            Mouse.Click(uIMyRefreshButtonButton, new Point(22, 11));

            // Click 'Ausblenden' button
            Mouse.Click(uIAusblendenButton, new Point(6, 6));
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow();
                }
                return this.mUIItemWindow;
            }
        }
        
        public UISimplicStudio2015spiWindow UISimplicStudio2015spiWindow
        {
            get
            {
                if ((this.mUISimplicStudio2015spiWindow == null))
                {
                    this.mUISimplicStudio2015spiWindow = new UISimplicStudio2015spiWindow();
                }
                return this.mUISimplicStudio2015spiWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        
        private UISimplicStudio2015spiWindow mUISimplicStudio2015spiWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Desktop";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32769";
            #endregion
        }
        
        #region Properties
        public UIAusgeführteAnwendungToolBar UIAusgeführteAnwendungToolBar
        {
            get
            {
                if ((this.mUIAusgeführteAnwendungToolBar == null))
                {
                    this.mUIAusgeführteAnwendungToolBar = new UIAusgeführteAnwendungToolBar(this);
                }
                return this.mUIAusgeführteAnwendungToolBar;
            }
        }
        #endregion
        
        #region Fields
        private UIAusgeführteAnwendungToolBar mUIAusgeführteAnwendungToolBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIAusgeführteAnwendungToolBar : WinToolBar
    {
        
        public UIAusgeführteAnwendungToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Ausgeführte Anwendungen";
            #endregion
        }
        
        #region Properties
        public WinButton UISimplicStudioButton
        {
            get
            {
                if ((this.mUISimplicStudioButton == null))
                {
                    this.mUISimplicStudioButton = new WinButton(this);
                    #region Search Criteria
                    this.mUISimplicStudioButton.SearchProperties[WinButton.PropertyNames.Name] = "Simplic Studio";
                    #endregion
                }
                return this.mUISimplicStudioButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUISimplicStudioButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISimplicStudio2015spiWindow : WpfWindow
    {
        
        public UISimplicStudio2015spiWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "Simplic Studio 2015 - spiegelburg gmbh [beggers]";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Simplic Studio 2015 - spiegelburg gmbh [beggers]");
            #endregion
        }
        
        #region Properties
        public UIStartPageCustom UIStartPageCustom
        {
            get
            {
                if ((this.mUIStartPageCustom == null))
                {
                    this.mUIStartPageCustom = new UIStartPageCustom(this);
                }
                return this.mUIStartPageCustom;
            }
        }
        
        public UIDataGridKeyboardContCustom UIDataGridKeyboardContCustom
        {
            get
            {
                if ((this.mUIDataGridKeyboardContCustom == null))
                {
                    this.mUIDataGridKeyboardContCustom = new UIDataGridKeyboardContCustom(this);
                }
                return this.mUIDataGridKeyboardContCustom;
            }
        }
        
        public UIRadGridViewTable UIRadGridViewTable
        {
            get
            {
                if ((this.mUIRadGridViewTable == null))
                {
                    this.mUIRadGridViewTable = new UIRadGridViewTable(this);
                }
                return this.mUIRadGridViewTable;
            }
        }
        
        public UIRadSplitContainerCustom UIRadSplitContainerCustom
        {
            get
            {
                if ((this.mUIRadSplitContainerCustom == null))
                {
                    this.mUIRadSplitContainerCustom = new UIRadSplitContainerCustom(this);
                }
                return this.mUIRadSplitContainerCustom;
            }
        }
        
        public UIM_gridSearchGridCustom1 UIM_gridSearchGridCustom
        {
            get
            {
                if ((this.mUIM_gridSearchGridCustom == null))
                {
                    this.mUIM_gridSearchGridCustom = new UIM_gridSearchGridCustom1(this);
                }
                return this.mUIM_gridSearchGridCustom;
            }
        }
        
        public UIDataGridRibbonContexCustom1 UIDataGridRibbonContexCustom
        {
            get
            {
                if ((this.mUIDataGridRibbonContexCustom == null))
                {
                    this.mUIDataGridRibbonContexCustom = new UIDataGridRibbonContexCustom1(this);
                }
                return this.mUIDataGridRibbonContexCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIStartPageCustom mUIStartPageCustom;
        
        private UIDataGridKeyboardContCustom mUIDataGridKeyboardContCustom;
        
        private UIRadGridViewTable mUIRadGridViewTable;
        
        private UIRadSplitContainerCustom mUIRadSplitContainerCustom;
        
        private UIM_gridSearchGridCustom1 mUIM_gridSearchGridCustom;
        
        private UIDataGridRibbonContexCustom1 mUIDataGridRibbonContexCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIStartPageCustom : WpfCustom
    {
        
        public UIStartPageCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.Window_Start";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "startPage";
            this.WindowTitles.Add("Simplic Studio 2015 - spiegelburg gmbh [beggers]");
            #endregion
        }
        
        #region Properties
        public UITileScrollViewerPane UITileScrollViewerPane
        {
            get
            {
                if ((this.mUITileScrollViewerPane == null))
                {
                    this.mUITileScrollViewerPane = new UITileScrollViewerPane(this);
                }
                return this.mUITileScrollViewerPane;
            }
        }
        #endregion
        
        #region Fields
        private UITileScrollViewerPane mUITileScrollViewerPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITileScrollViewerPane : WpfPane
    {
        
        public UITileScrollViewerPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfPane.PropertyNames.ClassName] = "Uia.ScrollViewer";
            this.SearchProperties[WpfPane.PropertyNames.AutomationId] = "tileScrollViewer";
            this.WindowTitles.Add("Simplic Studio 2015 - spiegelburg gmbh [beggers]");
            #endregion
        }
        
        #region Properties
        public WpfButton UIEreignisprotokollButton
        {
            get
            {
                if ((this.mUIEreignisprotokollButton == null))
                {
                    this.mUIEreignisprotokollButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIEreignisprotokollButton.SearchProperties[WpfButton.PropertyNames.Name] = "Ereignisprotokoll";
                    this.mUIEreignisprotokollButton.WindowTitles.Add("Simplic Studio 2015 - spiegelburg gmbh [beggers]");
                    #endregion
                }
                return this.mUIEreignisprotokollButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIEreignisprotokollButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDataGridKeyboardContCustom : WpfCustom
    {
        
        public UIDataGridKeyboardContCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.KeyboardController";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "dataGridKeyboardController";
            this.WindowTitles.Add("Simplic Studio 2015 - spiegelburg gmbh [beggers]");
            #endregion
        }
        
        #region Properties
        public UIDataGridRibbonContexCustom UIDataGridRibbonContexCustom
        {
            get
            {
                if ((this.mUIDataGridRibbonContexCustom == null))
                {
                    this.mUIDataGridRibbonContexCustom = new UIDataGridRibbonContexCustom(this);
                }
                return this.mUIDataGridRibbonContexCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIDataGridRibbonContexCustom mUIDataGridRibbonContexCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDataGridRibbonContexCustom : WpfCustom
    {
        
        public UIDataGridRibbonContexCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.RibbonContextController";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "dataGridRibbonContextController";
            this.WindowTitles.Add("Simplic Studio 2015 - spiegelburg gmbh [beggers]");
            #endregion
        }
        
        #region Properties
        public UIM_gridSearchGridCustom UIM_gridSearchGridCustom
        {
            get
            {
                if ((this.mUIM_gridSearchGridCustom == null))
                {
                    this.mUIM_gridSearchGridCustom = new UIM_gridSearchGridCustom(this);
                }
                return this.mUIM_gridSearchGridCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIM_gridSearchGridCustom mUIM_gridSearchGridCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIM_gridSearchGridCustom : WpfCustom
    {
        
        public UIM_gridSearchGridCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.IntegratedGridView";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "m_gridSearchGrid";
            this.WindowTitles.Add("Simplic Studio 2015 - spiegelburg gmbh [beggers]");
            #endregion
        }
        
        #region Properties
        public WpfButton UIVollständigladenButton
        {
            get
            {
                if ((this.mUIVollständigladenButton == null))
                {
                    this.mUIVollständigladenButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIVollständigladenButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "loadAllButton";
                    this.mUIVollständigladenButton.WindowTitles.Add("Simplic Studio 2015 - spiegelburg gmbh [beggers]");
                    #endregion
                }
                return this.mUIVollständigladenButton;
            }
        }
        
        public WpfButton UISaveLyoutButtonButton
        {
            get
            {
                if ((this.mUISaveLyoutButtonButton == null))
                {
                    this.mUISaveLyoutButtonButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUISaveLyoutButtonButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "saveLyoutButton";
                    this.mUISaveLyoutButtonButton.WindowTitles.Add("Simplic Studio 2015 - spiegelburg gmbh [beggers]");
                    #endregion
                }
                return this.mUISaveLyoutButtonButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIVollständigladenButton;
        
        private WpfButton mUISaveLyoutButtonButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIRadGridViewTable : WpfTable
    {
        
        public UIRadGridViewTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfTable.PropertyNames.HelpText] = "RadGridView";
            this.WindowTitles.Add("Simplic Studio 2015 - spiegelburg gmbh [beggers]");
            #endregion
        }
        
        #region Properties
        public UIPART_HeaderRowHeader UIPART_HeaderRowHeader
        {
            get
            {
                if ((this.mUIPART_HeaderRowHeader == null))
                {
                    this.mUIPART_HeaderRowHeader = new UIPART_HeaderRowHeader(this);
                }
                return this.mUIPART_HeaderRowHeader;
            }
        }
        
        public UISchweregradHeaderItem UISchweregradHeaderItem
        {
            get
            {
                if ((this.mUISchweregradHeaderItem == null))
                {
                    this.mUISchweregradHeaderItem = new UISchweregradHeaderItem(this);
                }
                return this.mUISchweregradHeaderItem;
            }
        }
        
        public WpfList UIGridViewGroupPanelList
        {
            get
            {
                if ((this.mUIGridViewGroupPanelList == null))
                {
                    this.mUIGridViewGroupPanelList = new WpfList(this);
                    #region Search Criteria
                    this.mUIGridViewGroupPanelList.SearchProperties[WpfList.PropertyNames.AutomationId] = "PART_GroupPanel";
                    this.mUIGridViewGroupPanelList.WindowTitles.Add("Simplic Studio 2015 - spiegelburg gmbh [beggers]");
                    #endregion
                }
                return this.mUIGridViewGroupPanelList;
            }
        }
        #endregion
        
        #region Fields
        private UIPART_HeaderRowHeader mUIPART_HeaderRowHeader;
        
        private UISchweregradHeaderItem mUISchweregradHeaderItem;
        
        private WpfList mUIGridViewGroupPanelList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIPART_HeaderRowHeader : WpfControl
    {
        
        public UIPART_HeaderRowHeader(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ControlType] = "Header";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "PART_HeaderRow";
            this.WindowTitles.Add("Simplic Studio 2015 - spiegelburg gmbh [beggers]");
            #endregion
        }
        
        #region Properties
        public WpfControl UIDatumHeaderItem
        {
            get
            {
                if ((this.mUIDatumHeaderItem == null))
                {
                    this.mUIDatumHeaderItem = new WpfControl(this);
                    #region Search Criteria
                    this.mUIDatumHeaderItem.SearchProperties[WpfControl.PropertyNames.ControlType] = "HeaderItem";
                    this.mUIDatumHeaderItem.SearchProperties[WpfControl.PropertyNames.AutomationId] = "Datum";
                    this.mUIDatumHeaderItem.WindowTitles.Add("Simplic Studio 2015 - spiegelburg gmbh [beggers]");
                    #endregion
                }
                return this.mUIDatumHeaderItem;
            }
        }
        #endregion
        
        #region Fields
        private WpfControl mUIDatumHeaderItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISchweregradHeaderItem : WpfControl
    {
        
        public UISchweregradHeaderItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ControlType] = "HeaderItem";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "Schweregrad";
            this.WindowTitles.Add("Simplic Studio 2015 - spiegelburg gmbh [beggers]");
            #endregion
        }
        
        #region Properties
        public WpfText UISchweregradText
        {
            get
            {
                if ((this.mUISchweregradText == null))
                {
                    this.mUISchweregradText = new WpfText(this);
                    #region Search Criteria
                    this.mUISchweregradText.SearchProperties[WpfText.PropertyNames.Name] = "Schweregrad";
                    this.mUISchweregradText.WindowTitles.Add("Simplic Studio 2015 - spiegelburg gmbh [beggers]");
                    #endregion
                }
                return this.mUISchweregradText;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUISchweregradText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIRadSplitContainerCustom : WpfCustom
    {
        
        public UIRadSplitContainerCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.RadSplitContainer";
            this.SearchProperties[WpfControl.PropertyNames.Name] = "Rad Split Container";
            this.WindowTitles.Add("Simplic Studio 2015 - spiegelburg gmbh [beggers]");
            #endregion
        }
        
        #region Properties
        public UIRadPaneGroupTabList UIRadPaneGroupTabList
        {
            get
            {
                if ((this.mUIRadPaneGroupTabList == null))
                {
                    this.mUIRadPaneGroupTabList = new UIRadPaneGroupTabList(this);
                }
                return this.mUIRadPaneGroupTabList;
            }
        }
        #endregion
        
        #region Fields
        private UIRadPaneGroupTabList mUIRadPaneGroupTabList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIRadPaneGroupTabList : WpfTabList
    {
        
        public UIRadPaneGroupTabList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfTabList.PropertyNames.AutomationId] = "myLayoutPanel";
            this.WindowTitles.Add("Simplic Studio 2015 - spiegelburg gmbh [beggers]");
            #endregion
        }
        
        #region Properties
        public UIEreignisprotokollTabPage UIEreignisprotokollTabPage
        {
            get
            {
                if ((this.mUIEreignisprotokollTabPage == null))
                {
                    this.mUIEreignisprotokollTabPage = new UIEreignisprotokollTabPage(this);
                }
                return this.mUIEreignisprotokollTabPage;
            }
        }
        
        public UIEreignisprotokollTabPage1 UIEreignisprotokollTabPage1
        {
            get
            {
                if ((this.mUIEreignisprotokollTabPage1 == null))
                {
                    this.mUIEreignisprotokollTabPage1 = new UIEreignisprotokollTabPage1(this);
                }
                return this.mUIEreignisprotokollTabPage1;
            }
        }
        #endregion
        
        #region Fields
        private UIEreignisprotokollTabPage mUIEreignisprotokollTabPage;
        
        private UIEreignisprotokollTabPage1 mUIEreignisprotokollTabPage1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIEreignisprotokollTabPage : WpfTabPage
    {
        
        public UIEreignisprotokollTabPage(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfTabPage.PropertyNames.Name] = "Ereignisprotokoll";
            this.WindowTitles.Add("Simplic Studio 2015 - spiegelburg gmbh [beggers]");
            #endregion
        }
        
        #region Properties
        public WpfButton UIAusblendenButton
        {
            get
            {
                if ((this.mUIAusblendenButton == null))
                {
                    this.mUIAusblendenButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIAusblendenButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "RadPaneCloseButton";
                    this.mUIAusblendenButton.WindowTitles.Add("Simplic Studio 2015 - spiegelburg gmbh [beggers]");
                    #endregion
                }
                return this.mUIAusblendenButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIAusblendenButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIEreignisprotokollTabPage1 : WpfTabPage
    {
        
        public UIEreignisprotokollTabPage1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfTabPage.PropertyNames.Name] = "Ereignisprotokoll";
            this.WindowTitles.Add("Simplic Studio 2015 - spiegelburg gmbh [beggers]");
            #endregion
        }
        
        #region Properties
        public WpfButton UIAusblendenButton
        {
            get
            {
                if ((this.mUIAusblendenButton == null))
                {
                    this.mUIAusblendenButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIAusblendenButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "RadPaneCloseButton";
                    this.mUIAusblendenButton.WindowTitles.Add("Simplic Studio 2015 - spiegelburg gmbh [beggers]");
                    #endregion
                }
                return this.mUIAusblendenButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIAusblendenButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIM_gridSearchGridCustom1 : WpfCustom
    {
        
        public UIM_gridSearchGridCustom1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.IntegratedGridView";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "m_gridSearchGrid";
            this.WindowTitles.Add("Simplic Studio 2015 - spiegelburg gmbh [beggers]");
            #endregion
        }
        
        #region Properties
        public UIRadGridViewTable1 UIRadGridViewTable
        {
            get
            {
                if ((this.mUIRadGridViewTable == null))
                {
                    this.mUIRadGridViewTable = new UIRadGridViewTable1(this);
                }
                return this.mUIRadGridViewTable;
            }
        }
        
        public WpfButton UISaveLyoutButtonButton
        {
            get
            {
                if ((this.mUISaveLyoutButtonButton == null))
                {
                    this.mUISaveLyoutButtonButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUISaveLyoutButtonButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "saveLyoutButton";
                    this.mUISaveLyoutButtonButton.WindowTitles.Add("Simplic Studio 2015 - spiegelburg gmbh [beggers]");
                    #endregion
                }
                return this.mUISaveLyoutButtonButton;
            }
        }
        #endregion
        
        #region Fields
        private UIRadGridViewTable1 mUIRadGridViewTable;
        
        private WpfButton mUISaveLyoutButtonButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIRadGridViewTable1 : WpfTable
    {
        
        public UIRadGridViewTable1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfTable.PropertyNames.HelpText] = "RadGridView";
            this.WindowTitles.Add("Simplic Studio 2015 - spiegelburg gmbh [beggers]");
            #endregion
        }
        
        #region Properties
        public UISchweregradListItem UISchweregradListItem
        {
            get
            {
                if ((this.mUISchweregradListItem == null))
                {
                    this.mUISchweregradListItem = new UISchweregradListItem(this);
                }
                return this.mUISchweregradListItem;
            }
        }
        #endregion
        
        #region Fields
        private UISchweregradListItem mUISchweregradListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISchweregradListItem : WpfListItem
    {
        
        public UISchweregradListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfListItem.PropertyNames.AutomationId] = "PART_Cell";
            this.WindowTitles.Add("Simplic Studio 2015 - spiegelburg gmbh [beggers]");
            #endregion
        }
        
        #region Properties
        public WpfButton UIPART_CloseButtonButton
        {
            get
            {
                if ((this.mUIPART_CloseButtonButton == null))
                {
                    this.mUIPART_CloseButtonButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIPART_CloseButtonButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "PART_CloseButton";
                    this.mUIPART_CloseButtonButton.WindowTitles.Add("Simplic Studio 2015 - spiegelburg gmbh [beggers]");
                    #endregion
                }
                return this.mUIPART_CloseButtonButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIPART_CloseButtonButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDataGridRibbonContexCustom1 : WpfCustom
    {
        
        public UIDataGridRibbonContexCustom1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.RibbonContextController";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "dataGridRibbonContextController";
            this.WindowTitles.Add("Simplic Studio 2015 - spiegelburg gmbh [beggers]");
            #endregion
        }
        
        #region Properties
        public UIM_gridSearchGridCustom2 UIM_gridSearchGridCustom
        {
            get
            {
                if ((this.mUIM_gridSearchGridCustom == null))
                {
                    this.mUIM_gridSearchGridCustom = new UIM_gridSearchGridCustom2(this);
                }
                return this.mUIM_gridSearchGridCustom;
            }
        }
        
        public UIM_searchBoxGridsCustom UIM_searchBoxGridsCustom
        {
            get
            {
                if ((this.mUIM_searchBoxGridsCustom == null))
                {
                    this.mUIM_searchBoxGridsCustom = new UIM_searchBoxGridsCustom(this);
                }
                return this.mUIM_searchBoxGridsCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIM_gridSearchGridCustom2 mUIM_gridSearchGridCustom;
        
        private UIM_searchBoxGridsCustom mUIM_searchBoxGridsCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIM_gridSearchGridCustom2 : WpfCustom
    {
        
        public UIM_gridSearchGridCustom2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.IntegratedGridView";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "m_gridSearchGrid";
            this.WindowTitles.Add("Simplic Studio 2015 - spiegelburg gmbh [beggers]");
            #endregion
        }
        
        #region Properties
        public WpfButton UIVollständigladenButton
        {
            get
            {
                if ((this.mUIVollständigladenButton == null))
                {
                    this.mUIVollständigladenButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIVollständigladenButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "loadAllButton";
                    this.mUIVollständigladenButton.WindowTitles.Add("Simplic Studio 2015 - spiegelburg gmbh [beggers]");
                    #endregion
                }
                return this.mUIVollständigladenButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIVollständigladenButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIM_searchBoxGridsCustom : WpfCustom
    {
        
        public UIM_searchBoxGridsCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.Control_SearchBox";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "m_searchBoxGrids";
            this.WindowTitles.Add("Simplic Studio 2015 - spiegelburg gmbh [beggers]");
            #endregion
        }
        
        #region Properties
        public WpfButton UIMyRefreshButtonButton
        {
            get
            {
                if ((this.mUIMyRefreshButtonButton == null))
                {
                    this.mUIMyRefreshButtonButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIMyRefreshButtonButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "myRefreshButton";
                    this.mUIMyRefreshButtonButton.WindowTitles.Add("Simplic Studio 2015 - spiegelburg gmbh [beggers]");
                    #endregion
                }
                return this.mUIMyRefreshButtonButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIMyRefreshButtonButton;
        #endregion
    }
}
